### ISSUE TITLE
Page 101 `ember g component star-rating` no longer creates the js file

### ISSUE THREAD

**Issue by lenoraporter** [rockandrollwithemberjs/rarwe-issues#453]
You'll need to run `ember generate component-class star-rating`

**Comment by balinterdi** [comment]
It seems like up to 3.14 `ember generate component` creates both files so in the pre-Octane book, the command in the book should be fine, I think.

I'm writing the Octane book now and there, I indeed need to generate the component class (or just use the `--with-component-class` switch).

**Comment by lenoraporter** [comment]
Looks like I'm jumping the gun! I can't wait to jump into the Octane book. Thanks a ton :)
