### ISSUE TITLE
resource URL for PATCH request

### ISSUE THREAD

**Issue by tibomogul** [rockandrollwithemberjs/rarwe-issues#454]
Page 113 says the URL would be `/bands/1` but should be `/bands/pearl-jam` based on the example.

**Comment by balinterdi** [comment]
Can you tell which book version? I looked at the latest Ember 3 and Ember Octane (Early Access) books but neither of them had such a URL on Page 113. Thank you.

**Comment by tibomogul** [comment]
Sorry @balinterdi , I was looking at the epub version. It is the Ember,.js 3 book (havent looked at the Octane one yet), on the PDF version it is in page 167.

**Comment by balinterdi** [comment]
Thanks, I've found it, in the "Talking to a backend" chapter, right?
