### ISSUE TITLE
Typo in adding to build assets p26 (Tachyons instead of Tailwind)

### ISSUE THREAD

**Issue by joelamb** [rockandrollwithemberjs/rarwe-issues#459]
Should be "Tailwind" rather than "Tachyons" on p26:

There are two ways to tell Broccoli to include the ~~Tachyons~~ Tailwind assets in our application.

**Comment by balinterdi** [comment]
Hey Joe, great spot, thank you.

The previous version used tachyons so this was a copy-paste error.

Will be fixed in the next book release, 3.19.
