### ISSUE TITLE
ember-set-helper does not support placeholder syntax anymore

### ISSUE THREAD

**Issue by lljr** [rockandrollwithemberjs/rarwe-issues#466]
It sets the value to `undefined` now. I asked in `ember-set-helper`'s repo and told me to take a look at:

https://github.com/pzuraq/ember-set-helper#setting-passed-values 

EDIT: This won't work also when trying to `get` the value from `InputEvent` like in page 92 in the book. I think you will need to use `ember-composoble-helpers`.

**Comment by belgoros** [comment]
I tried to use [ember-composable-helper](https://github.com/DockYard/ember-composable-helpers) as follows to add a new song:
```js
#bands/songs.hbs

<input
      type="text"
      class="px-4 py-2 text-gray-800 bg-white rounded-md"
      placeholder="Title"
      value={{this.title}}
      {{on "input" (pick "target.value" (set this.title))}}
    />
...
```
and it worked as needed.

**Comment by balinterdi** [comment]
Thanks, guys, I'll fix it in the next release. That's what I get for using unstable packages, I guess :D

**Comment by lljr** [comment]
Do you know if there is any plan in making these helpers built-in like `mut`? The `set` and `get` are way easier to understand than `mut`.

**Comment by balinterdi** [comment]
I'm lazy to dig up the RFC but Chris Garrett made one to deprecate `mut` – and, if I recall correctly, replace it with `set`. At the end it was decided that it'll not be deprecated in 4.0 as a lot of teams/apps depend on it.

By the way, I totally agree with you, `mut` should go.

**Comment by lljr** [comment]
I think a way to solve this could be by callin the `input` built-in component. You could use `@value` and set it to a variable (depends on the context whether it be set on a controller or component). That way the value is kept in sync and you fetch it inside the function that will use it. In this case `this.cancel` and `this.saveSong`.  In other words, it would look like this
```handlebars
<div class="mt-6 flex">
  <Input
    type="text"
    @value={{this.title}}
    class="text-gray-800 bg-white rounded-md py-2 px-4"
    placeholder="Title"

  />
  <button
    {{on "click" this.saveSong}}
    class="ml-4 px-4 py-2 rounded bg-purple-600 shadow-md hover:shadow-lg hover:text-white">
    Save
  </button>
  <button
    {{on "click" this.cancel}}
    class="ml-2 px-4 p-2 rounded bg-white border border-bg-purple-600 shadow-md text-purple-600 hover:shadow-lg">
    Cancel
  </button>
</div>
```

You could also do the same thing in chapter 8.
```handlebars
<h3 class="text-lg leading-6 font-medium text-gray-100">
  New band
</h3>
<div class="mt-6 grid grid-cols-1 row-gap-6 col-gap-4 sm:grid-cols-6">
  <div class="sm:col-span-4">
    <label
      for="name"
      class="block text-sm font-medium">Name</label>
    <div class="mt-1 relative rounded-md shadow-sm">
      <Input
        id="name"
        @value={{this.name}}
        type="text"
            class="w-full text-gray-800 bg-white border rounded-md py-2"

      />

    </div>
  </div>
  <div class="sm:col-span-4">
    <button
      type="button"
      class="px-4 py-2 rounded bg-purple-600 shadow-md hover:shadow-lg"
      {{on "click" this.saveBand}}
    >
      Save
    </button>
  </div>
</div>
```
Here it's used to save the bands name in `this.name`.

**Comment by balinterdi** [comment]
That's a totally fine way to do it indeed.

I chose to just keep using native `<input>` tags and define action handlers that extract the value from the event and assign it. My reason for doing this is that I feel like part of Octane is to "leverage the platform", to shy away from using Ember-specific bits where not necessary. (Also [see here](https://discuss.emberjs.com/t/ember-octane-and-2-way-binding-what-are-you-recommend/18092/2) for some discussion.)
