### ISSUE TITLE
Typo when talking about {{#each ...}}...{{else}}..{{/each}} construct

### ISSUE THREAD

**Issue by belgoros** [rockandrollwithemberjs/rarwe-issues#467]
Thank you so much for continuing the trip with Ember and publishing the Octane update version 👍.

On the page 56, right after modifying the `bands/band/songs.hbs` template as follows:
```hbs
{{#if @model.length}}
  <ul>
    {{#each @model as |song|}} 
      <li class="mb-2">
        {{song.title}}
        <span class="float-right">{{song.rating}}</span>
      </li>
    {{/each}}
  </ul>
{{else}}
  <p class="text-center">The band has no songs yet</p>
{{/if}}
```
you are writing:

> Notice the {{#each ...}}...{{else}}..{{/each}} construct above. The else branch is a nifty shorthand for the case when the collection the loop is iterating on turns out to be empty.

sure, it is a nifty shorthand probably used in previous versions of the book, but it is not used in the current context.
As you can see, instead we are using `if/else` block in the above code snippet.

Used in `rock-and-roll-with-ember-octane-20200624` version.

**Comment by balinterdi** [comment]
Thanks, great catch again, I revised that section.
