### ISSUE TITLE
Making a note about accessing routes that don't exist

### ISSUE THREAD

**Issue by Pjaerr** [rockandrollwithemberjs/rarwe-issues#468]
Loving the book, especially how it goes through the refactoring process!

Every now and then I spend some time scratching my head when I create a new band and then follow the refactoring only to have a bunch of ambiguous console errors as the page had refreshed but the route (EG: `/new-band/songs`) no longer existed. I figured it out relatively quickly but maybe it is worth making a note of this somewhere?

FWIW I am on *Talking to a back-end* chapter.

This might just be me not focusing enough but I thought it worth creating an issue in any case, feel free to close.

**Comment by balinterdi** [comment]
Thanks, that's a good idea, I added a short note about this that'll go into the next update.
