### ISSUE TITLE
Octane edition: use yarn instead of npm to install fontawesome

### ISSUE THREAD

**Issue by belgoros** [rockandrollwithemberjs/rarwe-issues#469]
On page 63, you used `npm` to install fontawesome dependencies:
```
npm install -D @fortawesome/free-regular-svg-icons @fortawesome/free-solid-svg-icons
```
I wonder why to use `npm` instead of `yarn` if we used it when creating the app in the very beginning. It creates another `package-lock.json`. Is it done intentionally? I used the following yarn command and it works the same:
```
yarn add -D @fortawesome/free-regular-svg-icons @fortawesome/free-solid-svg-icons
```

**Comment by balinterdi** [comment]
Thanks, great catch.

The problem, I now realize, is that we use `--yarn` when creating the app which shouldn't be there.

The book should use `npm` throughout as `yarn` is only recommended (and I'm using it "behind the scenes").
