### ISSUE TITLE
ember-set-helper fails to change start rating value

### ISSUE THREAD

**Issue by belgoros** [rockandrollwithemberjs/rarwe-issues#470]
I followed the steps in **chapter 6** to use `ember-set-helper` to enable changing songs star rating values and it does not seem to work properly: when clicking on a star to upvote or downvote a song, all the stars are to set to empty.
This is how it looks like before clicking the rating (Daughter song):
<img width="1403" alt="before" src="https://user-images.githubusercontent.com/83579/88161670-9041dd00-cc10-11ea-9b88-6f54e0d49fe4.png">

And this is how it looks after the click (see the same DAughter song):
<img width="1405" alt="after" src="https://user-images.githubusercontent.com/83579/88161725-a485da00-cc10-11ea-942f-aa08da51819f.png">

The code source is available [here](https://github.com/belgoros/rarwe). Thank you.

**Comment by balinterdi** [comment]
I'm going to go through the recent issues one by one but this really looks like it's caused by #466.

A new version of `ember-set-helper` no longer supports the placeholder syntax. In the released book/app version, it's still supported and that's why it works in the book.

**Comment by belgoros** [comment]
@balinterdi, thank you, it would be great 👍 . I'm using `1.0.1` version of ember-set-helper.

**Comment by balinterdi** [comment]
Yep, I already made a fix, thank you for pointing this out.
