### ISSUE TITLE
Mark properties only used as values of input tags as tracked

### ISSUE THREAD

**Issue by lljr** [rockandrollwithemberjs/rarwe-issues#471]
```handlebars
{{!-- app/templates/bands/new.hbs --}}

<input
 id="name"
 class="w-full text-gray-800 bg-white border rounded-md py-2 px-4"
value={{this.name}}
 {{on "input" (set this.name (get _ "target.value"))}}
 />
```

It's context only has 
```javascript
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { dasherize } from '@ember/string';
import { Band } from 'rarwe/routes/bands';

export default class BandsNewController extends Controller {
  @action
  saveBand() {
    new Band({ name: this.name, slug: dasherize(this.name)})
  }
}
```

Shouldn't the property be declared and tracked in its controller like `@tracked name = ''`

The js route file also uses the `name` property 

```javascript
import Route from '@ember/routing/route';

export default class BandsNewRoute extends Route {
  resetController(controller) {
    controller.name = '';
  }

}
```
How does that work? How does the route know of `this.name` if its not declared in the controller?

**Comment by balinterdi** [comment]
Good question – properties on the controller need not be declared. If it's used in the template, or in the route file, it will just work, just as in standard JavaScript.

It also doesn't need to be explicitly defined as tracked. Since its used from the template via `set`, its automatically tracked.

**Comment by balinterdi** [comment]
Going more deeply into this, I think it should be marked `tracked` and I'm not sure why I can get away with not doing it. So I posted a question on the discussion forum:

https://discuss.emberjs.com/t/why-do-i-not-need-to-mark-the-property-as-tracked/18093

**Comment by balinterdi** [comment]
I recommend reading that thread as people answered the question very well.

The gist of it is that marking the property as tracked is not enforced starting in 3.20 but that example just seems to work because of the behavior of the native `input` tag.

The example is "more correct" if we mark the property as tracked – if there was a `{{this.name}}` as a standalone value in the template, it wouldn't update otherwise.

**Comment by lljr** [comment]
@balinterdi to keep consistency, maybe adding `@tracked name` in the book example would be good?

**Comment by balinterdi** [comment]
That's exactly what I'll do – that's also why I renamed this issue to reflect that.
