### ISSUE TITLE
Page 201: typo when referencing @model={{band.slug}}

### ISSUE THREAD

**Issue by belgoros** [rockandrollwithemberjs/rarwe-issues#473]
On page 201 the book says:

> You could also argue that since the transition is to a leaf route, we should make that explicit in our template, by passing @route="bands.band.index", like this: <LinkTo @route="bands.band.index" @model={{band.slug}} >.

If I'm not mistaken, we removed `slug` from the `Band` model earlier in previous chapter(s), so shouldn't be `@model={{band.id}}`?

**Comment by balinterdi** [comment]
Great catch, thank you, will be fixed in the next version.
