### ISSUE TITLE
Property referencing in catalog.js (this.bands and this.songs)

### ISSUE THREAD

**Issue by lljr** [rockandrollwithemberjs/rarwe-issues#475]
Consider 
```javascript
import Service from '@ember/service';
import { tracked } from 'tracked-built-ins';
import { inject as service } from '@ember/service';

export default class CatalogService extends Service {
  @service router;

  storage = {};

  constructor() {
    super(...arguments);
    this.storage.bands = tracked([]);
    this.storage.songs = tracked([]);
  }

  add(type, record) {
    let collection = type === 'band' ? this.bands : this.songs;
    collection.push(record);

  }

  get bands() {
    return this.storage.bands;
  }

  get songs() {
    return this.storage.songs;
  }

  find(type, filterFn) {
    let collection = type === 'band' ? this.bands : this.songs;
    return collection.find(filterFn);
  }

}
```

`get bands` and `get songs` reference `this.storage` to access both `.bands` and `.songs`. If this is changed to 

```javascript

add(type, record) {
    let collection = type === 'band' ? this.storage.bands : this.storage.songs;
    collection.push(record);

  }

 find(type, filterFn) {
    let collection = type === 'band' ? this.storage.bands : this.storage.songs;
    return collection.find(filterFn);
  }
```
Works the same and is being consistent with `get bands` and `get songs` which access the instances dictionary.
Why do these (`find` and `add`)  originally don't access the instance's `this.storage` but work the same? I noticed that if I change `get bands` or `get songs` to just `return this.bands` or `return this.songs` it will throw an Error.

**Comment by balinterdi** [comment]
@lljr I might have used `this.storage.bands` and `this.bands` inconsistently but that's no longer the cause in the latest version (20200805). Could you verify that indeed this issue can now be closed?

**Comment by lljr** [comment]
yes it's ok now. I'll close it.
