### ISSUE TITLE
Update: $E[1].name = 'PJ' does not work, $E.context[1].name = 'PJ' works!

### ISSUE THREAD

**Issue by einnor** [rockandrollwithemberjs/rarwe-issues#478]
The album in the model of list of albums at index 1 in template cannot be accessed using `$E[1]`, but by`$E.context[1]` on the console.

<img width="1219" alt="Screenshot 2020-08-03 at 11 10 35" src="https://user-images.githubusercontent.com/4572221/89160707-29121a00-d57a-11ea-9070-1b65f145b939.png">

Inspecting the `$E` object, you can clearly see a `context` property that contains a list of bands.

<img width="1400" alt="Screenshot 2020-08-03 at 11 11 22" src="https://user-images.githubusercontent.com/4572221/89160879-7098a600-d57a-11ea-9b0b-8a85d19cc89d.png">

Just pointing this out for anyone who might face the same challenge, and for future updates on the book 😄

**Comment by balinterdi** [comment]
If what you refer to above is on page 35 of the book, here's the paragraph describing what should be assigned to $E:

> Next, click Route in the Objects column in the bands row and then the $E next to the currentModel property in the right sidebar (you will see the $E when you hover over currentModel).

So $E is the route's `currentModel` property, which is the array of bands. From your screenshot, it seems to me you've clicked the route itself (not its `currentModel` property), hence the difference.

**Comment by einnor** [comment]
@balinterdi Ah. Thanks for pointing this out. A little oversight on my end. Thank you for the prompt response. Amazing!
