### ISSUE TITLE
Inconsistent use of "addon" with package

### ISSUE THREAD

**Issue by GradedJestRisk** [rockandrollwithemberjs/rarwe-issues#480]
In one of the first mention of Ember add-on, contiguous with npm package, the word addon is susbtituted by package.
It's not a big deal, but using addon consistently may help the beginner I am not to be confused by npm package and Ember add-on.

p26 v20200624
> The first way is to use an Ember **addon** suited for that library. The second is to install the npm **package** and
then do some additional plumbing to integrate it into our app. While using an Ember specific **package** is the
simplest way to go, it has a few drawbacks

I suggest the following change
> While using an Ember **addon** is the simplest way to go, it has a few drawbacks.

And maybe you can define what is an add-on
> The first way is to use a **pre-packaged** library, named **addon** in Ember.

**Comment by balinterdi** [comment]
Great suggestion, you're right. I'll change it for the next release.
