### ISSUE TITLE
Use of ember server over ember serve is unclear

### ISSUE THREAD

**Issue by GradedJestRisk** [rockandrollwithemberjs/rarwe-issues#482]
Chapter 2 use `ember server` to build and start development server
> It also comes with a development server, which we can launch with the
ember server command:
$ ember **server**
Build successful (4656ms) – Serving on http://localhost:4200/

Chapter 3 use `ember serve` to achieve what seems the same goal
>$ ember **serve**
This command first builds the whole client-side application, then launches the development server on port 4200.

If they have a different behaviour, the subtle different syntax (ending r) may be highlighted to make sure people catch it.

**Comment by balinterdi** [comment]
Fortunately there's no difference between them, so I should stick to using one. It'll probably be `ember s`, which also works and is less typing. Thank you!
