### ISSUE TITLE
Code shows absolute import while text claims relative - Chapter 4 Routing

### ISSUE THREAD

**Issue by GradedJestRisk** [rockandrollwithemberjs/rarwe-issues#484]
> First, we import the configuration from the config/environment module via a relative import. A relative
> import is one that begins with a . or a .. and follows the rules of relative paths in UNIX operating systems.
> The absolute module names would be rarwe/router and rarwe/config/environment, respectively, so
> ./config/environment is a functioning module import from rarwe/router.

But the actual code is
`import config from 'rarwe/config/environment';`
I suggest
`import config from './config/environment';`

**Comment by balinterdi** [comment]
@GradedJestRisk Thank you, good spot.

**Comment by GradedJestRisk** [comment]
By the way, it's quite useful when the reader want to replace its own (non-working) file version with the book's one, and his repository name doesn't match `rarwe. Are you okay with readers [sharing their own code ](https://github.com/GradedJestRisk/ember-rocks/)? It's never mentioned in the book.

**Comment by GradedJestRisk** [comment]
I've turned the repository as private. 
Why not telling about it when allowing access to source code ?

**Comment by balinterdi** [comment]
@GradedJestRisk Thanks. You're totally right, I will.

**Comment by GradedJestRisk** [comment]
There's another import in Chapter 7 songs controller
`import { Song } from 'rarwe/routes/bands';`
Can be replaced by
`import { Song } from '../../../routes/bands';`
