### ISSUE TITLE
[nit-picking] Chapter 6 - Add note on rendering in component block form example 

### ISSUE THREAD

**Issue by GradedJestRisk** [rockandrollwithemberjs/rarwe-issues#487]
Chapter 6 introduce component block form, mentioning `rendering`
> The component can render the passed block via the {{yield}} helper invoked from the component's template, optionally passing back block variables to the invoking context.

But in the example there, there's no rendering, only returning value
> Instead of rendering the stars in the component (..) let's use the block form to allow the caller to customize what markup it renders. That means we should return (yield in Ember's component lingo) the stars property 

As [browser rendering](https://en.wikipedia.org/wiki/Browser_engine) usually involve graphic rendering, I ended up thinking rendering can include returning value, but I doubt that's teh case here.
>A browser engine (also known as a layout engine or rendering engine) is a core software component of every major web browser. The primary job of a browser engine is to transform HTML documents and other resources of a web page into an interactive visual representation on a user's device. 

I suggest to add
> In this very  example, there's no such rendering, only returning values.

**Comment by GradedJestRisk** [comment]
As I open may issues, tell me in case they're not adding value to the book

**Comment by balinterdi** [comment]
Good observation, thank you.
