### ISSUE TITLE
[Typo][Chapter 6] Missing word

### ISSUE THREAD

**Issue by GradedJestRisk** [rockandrollwithemberjs/rarwe-issues#488]
Component specification section
>We now have call the @onUpdate function from the component whenever one of the stars is clicked.

Look like there's a missing "to"
>We now have **to** call the @onUpdate function from the component whenever one of the stars is clicked.

By the way, I found some extra information could clarify the following section
> Clicking on one of the stars expresses the user's intent to update the rating of the song. We'll need to handle
the click and update the song's rating to the star's value that was clicked. 

Like 
> We don't need to update the stars appearance (regular/solid), as this is already implemented.

**Comment by balinterdi** [comment]
@GradedJestRisk Thank you, I've fixed this, much appreciated.
