### ISSUE TITLE
[Chapter 7] Song controller - Whole band object supplied in place of band's name

### ISSUE THREAD

**Issue by GradedJestRisk** [rockandrollwithemberjs/rarwe-issues#489]
version 20200805
In songs controller, this.model is passed through Song constructor as band in page 115 
```
let song = new Song({ title: this.title, band: this.model });
this.model.songs = [...this.model.songs, song];
```

Song constructor suggest the whole band is to be passed in bands.js page 47
```
export class Song {
  constructor({ title, rating, band }) {
    this.title = title;
    this.rating = rating || 0;
    this.band = band;
  }
}
```

But instantiation use band's name only in bands.js in page 47
```
    let blackDog = new Song({
      title: 'Black Dog',
      band: 'Led Zeppelin',
      rating: 3
    });
```
But 

I changed the code and it still works 
`let song = new Song({ title: this.title, band: this.model.name});`

**Comment by balinterdi** [comment]
Could you say which page that's on? Thank you.

**Comment by GradedJestRisk** [comment]
This is page 102 (version 20200805), under header `Building a store... I mean, a catalog`

**Comment by balinterdi** [comment]
Sorry, you indeed had.

On page 113, in the "Adding songs to the catalog" section, we change setting the `song.band` property from a string to an object:

<img width="823" alt="Screenshot 2020-09-18 at 11 27 25" src="https://user-images.githubusercontent.com/5022/93581959-1aed5100-f9a2-11ea-85d7-2b61af0e7b74.png">

So by page 115, we should be good.
