### ISSUE TITLE
import or not to import `fetch` in routes and services

### ISSUE THREAD

**Issue by belgoros** [rockandrollwithemberjs/rarwe-issues#495]
Reading **chapter 9**, I discovered that there the `fetch` was imported in `routes/bands.js` route (page 130, 136):
```js
//routes/bands.js
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';
import Band from 'rarwe/models/band';
import fetch from 'fetch';

export default class BandsRoute extends Route {
  @service catalog;

  async model() {
    let response = await fetch('/bands');
    let json = await response.json();
...
```

 and it was not the case in `routes/bands/band/songs.js` route (page 137):
```js
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';
import Song from 'rarwe/models/song';

export default class BandsBandSongsRoute extends Route {
  @service catalog;

  async model() {
    let band = this.modelFor('bands.band');
    let url = band.relationships.songs;
    let response = await fetch(url);
    let json = await response.json();
...
```
Both are using `fetch`. Even if I comment out the import in `bands` route, it still works without any errors. 

The same for `catalog.js` service, where we call `fetch` in `fetchAll` functcion, page **150**:
```js
import Service from '@ember/service';
import Band from 'rarwe/models/band';
import { tracked } from 'tracked-built-ins';
...
export default class CatalogService extends Service {
...
async fetchAll() {
    let response = await fetch('/bands');
    let json = await response.json();
..
```

So the question is should we still import the `fetch` in routes/services or not? What is the rule to follow?

**Comment by balinterdi** [comment]
Thank you for spotting this.

The `import fetch` line is a good-to-have for the reasons I read in [the README of the `ember-fetch` package](https://github.com/ember-cli/ember-fetch#why-is-this-wrapper-needed). I also link to this in the book:

> You might wonder why we need to import `fetch` when it's built into all modern browsers. The `ember-fetch` package (installed by default in all new Ember apps) adds a wrapper around `fetch` and that's what we import. If you want to learn more about why that's needed, see [here](https://github.com/ember-cli/ember-fetch#why-is-this-wrapper-needed).

However, I forgot to add it in the place you've found. Thank you, I'll update it for the next release.

**Comment by belgoros** [comment]
Cool, thank you so much for making it clearer and providing the link to the reason of that.
