### ISSUE TITLE
Chapter 11 test failing on :first-child and :last-child selectors

### ISSUE THREAD

**Issue by cedriclinares** [rockandrollwithemberjs/rarwe-issues#498]
I am at the part where we install ember-test-selectors. I've added the data-test-rr attribute in each file but when I run the test I get this error 
![Screen Shot 2020-11-12 at 9 49 19 AM (2)](https://user-images.githubusercontent.com/4663143/98976600-661c6f80-24cc-11eb-999d-0d3fdc308269.png)

I tried with the most recent version of ember-test-selectors (5.0.0) and also the version in the github repo (4.1.0) and got the error on both versions. Please help.

**Comment by balinterdi** [comment]
Hey Cedric,

You have `firstchild` and `lastchild` as opposed to `first-child` and `last-child` in your selectors (which are indeed not valid :) ).

**Comment by cedriclinares** [comment]
Lol. I starred at this for a while and still didn't catch that. Thank you!

**Comment by balinterdi** [comment]
No worries, it happens to all of us :)
