### ISSUE TITLE
Tailwindcss needs autoprefixer and postcss when doing npm install

### ISSUE THREAD

**Issue by iamajvillalobos** [rockandrollwithemberjs/rarwe-issues#499]
I was previously using yarn on the sample application. Then I decided to just use npm on another app I'm building to learn more. I hit a snag on installing tailwind:

```
$ npm install -D tailwindcss

npm WARN tailwindcss@2.0.1 requires a peer of autoprefixer@^10.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN tailwindcss@2.0.1 requires a peer of postcss@^8.0.9 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-nested@5.0.2 requires a peer of postcss@^8.1.5 but none is installed. You must install peer dependencies yourself.
```

This doesn't show when I use yarn. So the proper command at this stage when using npm is:

```
$ npm install -D tailwindcss autoprefixer postcss
```

If you don't do this and after you setup the Postcss config and tried to start the server, you'll get this error:

```
ember s
Build Error (PostcssCompiler)

[object Object] is not a PostCSS plugin


Stack Trace and Error Report: /var/folders/xy/_t7556xs6md9s1sh3t8y92dm0000gn/T/error.dump.5adeca15863a1182345d81279d21228c.log
```

**Comment by balinterdi** [comment]
Thank you very much for pointing this out.

Under the hood I also use Yarn for building the app which I think is the only difference between how my readers build it and how I do. It could be time to replace Yarn with npm as the latter has come a long way recently.

I'll fix it one way or another for the next release.

**Comment by balinterdi** [comment]
I've checked this now, using npm instead of yarn and it seems to work just fine - I don't see any of the error messages you mention. I'm using npm 6.13.4 and node 12.16.1 . What version of these do you use?

**Comment by iamajvillalobos** [comment]
Sorry for the late reply. I tested it again with these versions:

```
node v14.15.3
ember-cli: 3.23.0
npm: 6.14.9
```

It works as the book does. The only problem I encountered is when I generate a `tailwind.config.js` to use purgecss, I need to add `autoprefixer`.

**Comment by balinterdi** [comment]
As we don't use purgecss in the book, I'm going to mark this as fixed (and then eventually close it), unless you tell me I shouldn't. Thank you for your feedback.
