### ISSUE TITLE
Typo on page 56 regarding the #each - else  (ver. 20201127)

### ISSUE THREAD

**Issue by emirpecanin** [rockandrollwithemberjs/rarwe-issues#501]
> Handlebars has a nifty extension of the **#else** helper. It has an else branch whose contents gets rendered ...

Shouldn't it be:
> Handlebars has a nifty extension of the **#each** helper...

**Comment by balinterdi** [comment]
Yes, it should, thank you for spotting this. (Will be fixed in the next release.)
