### ISSUE TITLE
Page 30 add / subtract code is highlighted incorrectly

### ISSUE THREAD

**Issue by sreninc** [rockandrollwithemberjs/rarwe-issues#502]
Lines 2-4  were removed in a prior step
Lines 15-21 and 24-26 were created in a prior step already

**Comment by balinterdi** [comment]
Hey Sean,

Thank you. It's interesting because actually these snippets are not generated manually but by git so git must think that those lines hadn't been removed earlier, and that's why it removes them again. I'll figure something out.

**Comment by balinterdi** [comment]
Problem found and fixed. Surprisingly, it was a user error: the tool worked fine but I didn't use it correctly :) Thank you for spotting this, I'm glad to have this fixed.

**Comment by balinterdi** [comment]
(This will be fixed in the next release.)
