### ISSUE TITLE
Page 225 - Typo "one" vs "once"

### ISSUE THREAD

**Issue by FlorSanders** [rockandrollwithemberjs/rarwe-issues#506]
On page 225, the last sentence states:

> Consequently, we have to check whether the transition is an aborted **one**, and
then bail out early

I suppose the **one** should be **once**

**Comment by balinterdi** [comment]
No, I meant to say, we have to check whether the transition is an aborted *transition*.

**Comment by FlorSanders** [comment]
Oh, reading it again that does make a lot more sense.
My appologies, I’ll close this issue.

**Comment by balinterdi** [comment]
No worries, Flor.
