### ISSUE TITLE
Page 351 - No changes from page 345

### ISSUE THREAD

**Issue by FlorSanders** [rockandrollwithemberjs/rarwe-issues#507]
At page 351, the goal is to refactor the code such that the capitalize() function can also be used in the rest of the application as a util.
However, the function had already been split of at page 345, so there are no changes in the code fragment.

**Comment by balinterdi** [comment]
Hey Flor,

Thank you very much both for this and #508 . Both are now fixed and will be published in the next book update.

**Comment by balinterdi** [comment]
Hey Flor,

Thank you for closing the issues. I usually prefer to keep them open until the next book update to prevent multiple reporting of the same issue. No worries, of course, I'll reopen them.
