### ISSUE TITLE
Page 94 – 95: Typo in version 20211015

### ISSUE THREAD

**Issue by leighfall** [rockandrollwithemberjs/rarwe-issues#516]
The sentence “More precisely, the collection it returns would need to be made **react** to changes by re-rendering.” I believe should read as “More precisely, the collection it returns would need to be made **reactive** to changes by re-rendering.” Or “More precisely, the collection it returns would need to be made **to react** to changes by re-rendering."

**Comment by balinterdi** [comment]
Thank you, Autumn. I've fixed this and it'll be in the next version of the book.
