### ISSUE TITLE
Clarification needed for mirage/config.js for 'List bands' test

### ISSUE THREAD

**Issue by waihon** [rockandrollwithemberjs/rarwe-issues#521]
The test `visit('/')` but the `mirage/config.js` only has below shorthand handers:
```
this.get('/bands');
this.get('/bands/:id');
```
Could you please clarify how would `visit('/')` gets mapped to the handlers in `mirage/config.js`, which doesn't have `this.get('/');`, for example?

**Comment by balinterdi** [comment]
I've added a paragraph to the book to clarify this:

> A common source of confusion is that both your Ember app and Mirage define "request paths" they serve. However, your Ember app define routes (or pages) that map to URLs that the app renders whereas Mirage works as your mock back-end and defines endpoints that your real back-end does. In REST-like APIs, these two might be very similar (you can have a page, accessible at `/bands` that hits an API endpoint at `/bands` to fetch a list of bands) but conceptually they are very different. The Ember app is the front-end, Mirage, the (mock) back-end.

Does that make sense?

**Comment by waihon** [comment]
Thank you for the clarification! That makes sense to me now.
