### ISSUE TITLE
Clarification needed for Ember.js string's capitalize function

### ISSUE THREAD

**Issue by waihon** [rockandrollwithemberjs/rarwe-issues#523]
On page 272, it's mentioned:
> We only call capitalize on the first character of each word because we want to allow songs that are in all caps, like MFC from Pearl Jam. If we called capitalize on each full word, users would not be able to create such a song title.

The Ember.js documentation at https://api.emberjs.com/ember/3.28/classes/String/methods/capitalize?anchor=capitalize give an example that illustrate only the first character of a string will be converted to uppercase while the remaining will be status quo:
> `capitalize('innerHTML')                 // 'InnerHTML'`

If that's the case, do we still need to explicitly call the capitalize function only on the first character?

**Comment by balinterdi** [comment]
That's a great point, thank you! I'll simplify this for the next release.

The helper is now just:

```js
import { helper } from '@ember/component/helper';
import { capitalize as emberCapitalize } from '@ember/string';

export function capitalize(input) {
  return input[0].split(/\s+/).map(emberCapitalize).join(' ');
}

export default helper(capitalize);
```
