### ISSUE TITLE
Errata in chapter Routing

### ISSUE THREAD

**Issue by ArianJM** [rockandrollwithemberjs/rarwe-issues#527]
Hi!

Just found an errata on the chapter "Routing", section "Routes set up data". The first paragraph after the code snippet for `app/router.js` contains "from from".
> First, we import the configuration from `rarwe/config/environment` which is the module created **from from** the `config/environment.js` module via a relative import.

This is in the latest version `20220218`.

**Comment by balinterdi** [comment]
Thank you, this will be fixed in the next release.
