### ISSUE TITLE
New songs are not saved on the back-end

### ISSUE THREAD

**Issue by balinterdi** [rockandrollwithemberjs/rarwe-issues#530]
As reported by @cg-fnba:

"At the end of chapter 9, should new songs be persisting on the back end? New bands are, but songs are not, for me. I have compared my catalog service and my songs controller with the one in the appropriate tag in your repository and they are identical.

After saving, status says 201 Created.

This is my payload:

```
{data: {type: "songs", attributes: {title: "Another Song"},…}}
data: {type: "songs", attributes: {title: "Another Song"},…}
attributes: {title: "Another Song"}
title: "Another Song"
relationships: {band: {data: {id: "another-band", type: "bands"}}}
band: {data: {id: "another-band", type: "bands"}}
data: {id: "another-band", type: "bands"}
type: "songs"
```
"

**Comment by balinterdi** [comment]
@cg-fnba Indeed when I checked out the repo at that commit, the songs failed to be saved on the back-end:

https://capture.dropbox.com/jSpb9VfKvcn34JN0

**Comment by balinterdi** [comment]
@cg-fnba This is fixed now - it was a back-end error. I recently upgraded the back-end and lost a piece of code in the process which made this work 😅

**Comment by cg-fnba** [comment]
Thank you! What are you using for the back-end?

**Comment by balinterdi** [comment]
It's a simple Rails app with jsonapi-resources as the library (gem) to provide JSON::API support.

**Comment by balinterdi** [comment]
I have fixed this and even blogged about it :D
https://devjournal.balinterdi.com/dont-fix-the-same-problem-twice/
