### ISSUE TITLE
Reword a sentence in Ch 11

### ISSUE THREAD

**Issue by mcculleydj** [rockandrollwithemberjs/rarwe-issues#531]
Sorry if this is a duplicate, I tried looking for a similar issue before posting this.
Pg 223 (text) or 230 (PDF) on the latest version

> Another thing I'd test is the load method as it many code paths run through it.

Pretty sure you were going for "...as it has many code paths running through it." or something to that effect. Great book btw.

**Comment by balinterdi** [comment]
Thank you, the "has" was indeed missing. This will be fixed in the next book update.
