### ISSUE TITLE
Missing close parenthesis in publication 20211015

### ISSUE THREAD

**Issue by laurenolivia** [rockandrollwithemberjs/rarwe-issues#533]
Chapter 6: Components
Page: 62

"In Ember templates, results of function calls cannot be rendered (if you'd like to learn more about why that is
so, read the "On the utility of explicit dependency definitions" section in the Appendix`)`. That's why we needed
to define a property, stars."

**Comment by balinterdi** [comment]
Thank you, I've fixed this now.
