### ISSUE TITLE
Terminal command typo in publication 20211015

### ISSUE THREAD

**Issue by laurenolivia** [rockandrollwithemberjs/rarwe-issues#535]
Chapter 6: Components
Page: 64
Printed 2xs `@fortawesome/free-regular-svg-icons`

`$ npm install -D @fortawesome/free-regular-svg-icons @fortawesome/free-solidsvg-icons`

**Comment by balinterdi** [comment]
It seems good to me, am I missing something?

<img width="979" alt="Screenshot 2022-03-25 at 12 45 12" src="https://user-images.githubusercontent.com/5022/160115072-726ef984-4950-44b1-894d-6c2f49e55fed.png">

**Comment by laurenolivia** [comment]
For some reason, the command returned a 404 so I had to separate the commands and run 
`npm install -D @fortawesome/free-regular-svg-icons`

I will try again and send an update

**Comment by laurenolivia** [comment]
Ah, I see the detail I overlooked is one calls for `free-regular` and the other `free-solid`. Will try again.

**Comment by balinterdi** [comment]
Oh, I misunderstood, I thought you were saying that I had `@fortawesome/free-regular-svg-icons` twice in the command.

The commands are actually run on my laptop so there's little chance they don't work but as we know computers are ... computers, so I wouldn't totally be surpised :D

**Comment by laurenolivia** [comment]
Yea this commands returns a 404 error. I don't know why there's an `@` symbol at the end of the command.
`npm install -D @fortawesome/free-solidsvg-icons`

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2ffree-solidsvg-icons - Not found
npm ERR! 404 
npm ERR! 404  '@fortawesome/free-solidsvg-icons@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url

**Comment by balinterdi** [comment]
You have a missing dash in the package name between "solid" and "svg": `@fortawesome/free-solidsvg-icons`

I double-checked in the book and it's correct there so you might have lost when copy-pasting the command.

**Comment by laurenolivia** [comment]
Ooooo typo in my command! We are good to go! Thanks.
