### ISSUE TITLE
Confusing Code Block (Pg. 148, "Making it shippable")

### ISSUE THREAD

**Issue by pearsehutson** [rockandrollwithemberjs/rarwe-issues#538]
Book Version 20220408, Pg. 148, Chapter 9, "Making it shippable"

The code block on page 148 is confusing because it combines changes from the top of the file and the middle of the file.
![image](https://user-images.githubusercontent.com/97191069/164087585-e2178ddc-ab2f-4cd3-b6d8-b3fb1ef7d2ef.png)

This led me to believe the `fetchRelated` method was supposed to be above the class. 

I would appreciate a separate code block, or a comment to differentiate the two parts of the file.

**Comment by balinterdi** [comment]
True, good point, I'll fix this for the next version. Thank you.
