### ISSUE TITLE
Update to Tailwind 3

### ISSUE THREAD

**Issue by balinterdi** [rockandrollwithemberjs/rarwe-issues#543]
This also means describing in detail how to set up Tailwind as it involves creating and tweaking the config file and ember-cli-build.js

**Comment by MichalBryxi** [comment]
Given that it's [marked as part of the 4.4 release](https://github.com/rockandrollwithemberjs/rarwe-issues/releases/tag/4.4) should this issue be closed?

**Comment by balinterdi** [comment]
You're right, I forgot that step, thank you!
